- hosts: jumpbox
  gather_facts: no
  become: yes
  roles:
     - bastion
     - osp-network
     - osp-keypair
     - osp-securitygroup
     - osp-flavor


  tasks:
  - name: Download RHEL image
    get_url:
      url: http://www.opentlc.com/download/osp_advanced_networking/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
      dest: /tmp/rhel.qcow2
  - os_image:
      cloud: ospcloud
      name: rhel-guest
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /tmp/rhel.qcow2
  ##Create Fronend Instance
  - name: Create frontend instance
    include_role:
       name: osp-instances
       vars_from: frontend.yaml
###Create App1 server 
  - name: Create app1 instance
    include_role:
       name: osp-instances
       vars_from: app1.yaml
##Create App2 server
  - name: Create app2 instance
    include_role:
       name: osp-instances
       vars_from: app2.yaml
##Create DB server
  - name: Create db instance
    include_role:
       name: osp-instances
       vars_from: db.yaml
  - name: Gather facts
    include_role: 
       name: osp-facts
    tags: testli

