---
# tasks file for osp-keypair
  - name: Generate key files
    user:
      #name: "{{ ansible_env.USER }}"
      name: cloud-user
      generate_ssh_key: yes
      ssh_key_file: .ssh/test_id_rsa
  - os_keypair:
      cloud: ospcloud
      state: present
      name: ansible_ssh
      public_key_file: "/home/cloud-user/.ssh/test_id_rsa.pub"
